ALTER VIEW VWPARCELASAFT AS
SELECT ISNULL(TCB.DESCRICAO,'') AS DESCRICAO,
       ISNULL(ITE.VALOR,0) AS VALOR,
       FORMAT(ISNULL(ORD.DHPREVCGD,''),'yyyy-MM-dd') AS DTVENC,
       CASE WHEN ITE.CODTIPCOB = 2 THEN 1
            WHEN ITE.CODTIPCOB  = 3 THEN 2
            ELSE 4 END AS TIPPARCELA,
       CASE WHEN AFT.FORMAPGTOADIANT = 'D' THEN 2
            WHEN AFT.FORMAPGTOADIANT = 'C' THEN 1
            ELSE 0 END AS FORMAPGTO,
       ISNULL(AFT.CODBCOADIANT,0) AS CODBCO,
       ISNULL(AFT.AGENCIAADIANT,0) AS CODAG,
       ISNULL(AFT.CONTAADIANT,0) AS NUMCTA,
       CASE WHEN AFT.TIPOCONTAADIANT = 'P' THEN 'S'
            ELSE 'N' END AS CTAPOUP,
       AFT.ORDEMCARGA,
       AFT.CODAFT,
       AFT.CODEMP,
       ROW_NUMBER() OVER (ORDER BY TIPOCONTAADIANT ASC) AS NROPARCELA
FROM TMSTIPCOBAFT TCB
         INNER JOIN TMSORDAFTITE ITE ON ITE.CODTIPCOB = TCB.CODTIPCOB
         INNER JOIN TMSORDAFT AFT ON AFT.CODAFT = ITE.CODAFT
         INNER JOIN TGFORD ORD ON ORD.ORDEMCARGA = AFT.ORDEMCARGA AND ORD.CODEMP = AFT.CODEMP
WHERE AFT.CODAFT = ? AND AFT.ORDEMCARGA = ? AND AFT.CODEMP = ? AND ITE.CODTIPCOB IN (2,3)