ALTER VIEW VWDADOSMOTTMS AS
SELECT ISNULL(SUBSTRING(NOMEPARC,0,CHARINDEX(' ',NOMEPARC)),'') AS NOME,
       ISNULL(SUBSTRING(NOMEPARC,CHARINDEX(' ',NOMEPARC) + 1,99),'') AS SOBRENOME,
       ISNULL(PAR.CGC_CPF,'') AS CPF,
       ISNULL(PAR.AD_NUMRG,'') AS NRORG,
       ISNULL(PAR.EMISSORRG,'') AS EMISSORRG,
       ISNULL(FORMAT(PAR.DTNASC,'yyyy-MM-dd'),'') AS DTNASC,
       ISNULL(PAR.SEXO,'') AS SEXO,
       ISNULL(CASE WHEN PAR.TIMESTADOCIVIL = 'SO' THEN 1
                   WHEN PAR.TIMESTADOCIVIL = 'CA' THEN 2
                   WHEN PAR.TIMESTADOCIVIL = 'VI' THEN 3
                   WHEN PAR.TIMESTADOCIVIL = 'DI' THEN 5
                   WHEN PAR.TIMESTADOCIVIL = 'SJ' THEN 6
                   ELSE 0 END,'') AS ESTADOCIVIL,
       ISNULL(CPL.PAI,'') AS PAI,
       ISNULL(CPL.MAE,'') AS MAE,
       ISNULL(PAR.EMAIL,'') AS EMAIL,
       ISNULL(PAR.TELEFONE,'') AS TELEFONE,
       ISNULL(PAR.TIMTELEFONE01,'') AS TIMTELEFONE01,
       ISNULL(PAR.TIMNACIONALIDAD,'') AS TIMNACIONALIDAD,
       ISNULL(END1.NOMEEND,'') AS NOMEEND,
       ISNULL(PAR.NUMEND,'') AS NUMEND,
       ISNULL(PAR.CEP,'') AS CEP,
       ISNULL(BAI.NOMEBAI,'') AS NOMEBAI,
       ISNULL(CID.NOMECID,'') AS NOMECID,
       ISNULL(UFS.UF,'') AS UF,
       ISNULL(CID.CODMUNFIS,'') AS CODMUNFIS,
       ISNULL(AFT.CODBCOADIANT,0) AS CODBCOADIANT,
       ISNULL(AFT.AGENCIAADIANT,0) AS AGENCIAADIANT,
       ISNULL(AFT.DIGITOADIANT,0) AS DIGITOADIANT,
       ISNULL(AFT.CONTAADIANT,0) AS CONTAADIANT,
       ISNULL(AFT.ORDEMCARGA,0) AS ORDEMCARGA,
       ISNULL(AFT.CODEMP,0) AS CODEMP,
       ISNULL(AFT.CODAFT,0) AS CODAFT
FROM TGFPAR PAR
         LEFT JOIN TGFCPL CPL ON CPL.CODPARC = PAR.CODPARC
         INNER JOIN TSIEND END1 ON END1.CODEND = PAR.CODEND
         INNER JOIN TSIBAI BAI ON BAI.CODBAI = PAR.CODBAI
         INNER JOIN TSICID CID ON CID.CODCID = PAR.CODCID
         INNER JOIN TSIUFS UFS ON UFS.CODUF = CID.UF
         INNER JOIN TGFORD ORD ON ORD.CODPARCMOTORISTA = PAR.CODPARC
         INNER JOIN TMSORDAFT AFT ON AFT.ORDEMCARGA = ORD.ORDEMCARGA AND AFT.CODEMP = ORD.CODEMP;