alter VIEW VWDADOSTRANSTMS AS
SELECT ISNULL(PAR.RNTRC,'') AS RNTRC,
       ISNULL(PAR.CGC_CPF,'') AS CGC_CPF,
       ISNULL(PAR.NOMEPARC,'') AS NOMEPARC,
       ISNULL(PAR.RAZAOSOCIAL,'') AS RAZAOSOCIAL,
       FORMAT(ISNULL(PAR.DTNASC,''), 'yyyy-MM-dd') AS DTNASC,
       ISNULL(PAR.AD_NUMRG,'') AS AD_NUMRG,
       ISNULL(PAR.EMISSORRG,'') AS EMISSORRG,
       ISNULL(PAR.SEXO,'S') AS SEXO,
       ISNULL(PAR.TIMNACIONALIDAD,'') AS TIMNACIONALIDAD,
       FORMAT(ISNULL(PAR.DTCAD,''), 'yyyy-MM-dd') AS DTCAD,
       ISNULL(PAR.NUMEND,'') AS NUMEND,
       ISNULL(PAR.CEP,'') AS CEP,
       ISNULL(PAR.COMPLEMENTO,'') AS COMPLEMENTO,
       ISNULL(PAR.TELEFONE,'0') AS TELEFONE,
       ISNULL(PAR.TIMTELEFONE01,'0') AS TIMTELEFONE01,
       CASE WHEN PAR.TIMESTADOCIVIL = 'SO' THEN 1
            WHEN PAR.TIMESTADOCIVIL = 'CA' THEN 2
            WHEN PAR.TIMESTADOCIVIL = 'VI' THEN 3
            WHEN PAR.TIMESTADOCIVIL = 'DI' THEN 5
            WHEN PAR.TIMESTADOCIVIL = 'SJ' THEN 6
            ELSE 0 END AS TIMESTADOCIVIL,
       ISNULL(PAR.EMAIL,'') AS EMAIL,
       ISNULL(PAR.CGC_CPF,'') AS USUARIO,
       ISNULL(CPL.NROCNH,'') AS NROCNH,
       ISNULL(CPL.CATEGORIACNH,'') AS CATEGORIACNH,
       FORMAT(ISNULL(CPL.VENCIMENTOCNH,''), 'yyyy-MM-dd') AS VENCIMENTOCNH,
       ISNULL(CPL.NATURALIDADE,'') AS NATURALIDADE,
       ISNULL(PAR.IDENTINSCESTAD,'') AS IDENTINSCESTAD,
       ISNULL(END1.NOMEEND,'') AS NOMEEND,
       ISNULL(BAI.NOMEBAI,'') AS NOMEBAI,
       ISNULL(ORD.CODPARCPROPANTT,'') AS CODPARCPROPANTT,
       ISNULL(AFT.CODBCOADIANT,0) AS CODBCOADIANT,
       ISNULL(AFT.AGENCIAADIANT,0) AS AGENCIAADIANT,
       ISNULL(AFT.DIGITOADIANT,0) AS DIGITOADIANT,
       ISNULL(AFT.CONTAADIANT,0) AS CONTAADIANT,
       ISNULL(AFT.ORDEMCARGA,0) AS ORDEMCARGA,
       ISNULL(AFT.CODEMP,0) AS CODEMP,
       ISNULL(AFT.CODAFT,0) AS CODAFT,
       ISNULL(CID.CODMUNFIS,0) AS CODIBGE
FROM TGFPAR PAR
         INNER JOIN TGFCPL CPL ON CPL.CODPARC = PAR.CODPARC
         INNER JOIN TSIEND END1 ON END1.CODEND = PAR.CODEND
         INNER JOIN TSIBAI BAI ON BAI.CODBAI = PAR.CODBAI
         INNER JOIN TGFORD ORD ON ORD.CODPARCPROPANTT = PAR.CODPARC
         INNER JOIN TMSORDAFT AFT ON AFT.ORDEMCARGA = ORD.ORDEMCARGA AND AFT.CODEMP = ORD.CODEMP
         INNER JOIN TSICID CID ON CID.CODCID = PAR.CODCID;