ALTER VIEW VWDADOSPARTTMS AS
SELECT ISNULL(PAR.NOMEPARC, '')      AS NOMEPARC,
       ISNULL(PAR.RAZAOSOCIAL, '')   AS RAZAOSOCIAL,
       ISNULL(PAR.CGC_CPF, '')       AS CNPJCPF,
       ISNULL(END1.NOMEEND, '')      AS ENDERECO,
       ISNULL(BAI.NOMEBAI, '')       AS BAIRRO,
       ISNULL(PAR.CEP, '')           AS CEP,
       ISNULL(PAR.RNTRC, '')         AS RNTRC,
       ISNULL(PAR.EMAIL, '')         AS EMAIL,
       ISNULL(PAR.TELEFONE, '')      AS TELEFONE,
       ISNULL(PAR.TIMTELEFONE01, '') AS TELEFONECELULAR,
       CASE
           WHEN PAR.TIPPESSOA = 'F' THEN 1
           WHEN PAR.TIPPESSOA = 'J' THEN 2
           ELSE '' END               AS TIPPESSOA,
       ISNULL(CID.CODMUNFIS, 0)      AS CODMUNFIS,
       CAB.ORDEMCARGA,
       CAB.CODEMP
FROM TGFCAB CAB
         LEFT JOIN TGFPAR PAR ON PAR.CODPARC = (CASE WHEN CAB.CODPARCREDESPACHO = 0
                                                         THEN CAB.CODPARCDEST ELSE CAB.CODPARCREDESPACHO END)
         LEFT JOIN TSIEND END1 ON END1.CODEND = PAR.CODEND
         LEFT JOIN TSICID CID ON CID.CODCID = PAR.CODCID
         LEFT JOIN TSIBAI BAI ON BAI.CODBAI = PAR.CODBAI
         LEFT JOIN TGFORD ORD ON ORD.ORDEMCARGA = CAB.ORDEMCARGA
         LEFT JOIN TGFROT ROT ON ROT.CODCIDDEST = PAR.CODCID